tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "bash-completion"
brew "exiftool"
brew "gcc"
brew "gifsicle"
brew "git"
brew "go"
brew "krb5"
brew "kubernetes-cli"
brew "kubectx"
brew "mysql"
brew "node", link: false
brew "nvm"
brew "onepass"
brew "postgresql", restart_service: true
brew "python@3.9"
brew "redis", restart_service: true
brew "stern"
brew "watch"
brew "wget"
brew "yadm"
brew "yarn"
brew "zsh-syntax-highlighting"
brew "heroku/brew/heroku"
cask "bitwarden"
cask "chromedriver"
cask "font-source-code-pro"
cask "rectangle"
cask "iterm2"
cask "font-hack-nerd-font"
cask "font-inconsolata-for-powerline"
cask "font-menlo-for-powerline"
